# Status Bar Configuration
# 状态栏配置
#
# Configure the status bar appearance and behavior
# 配置状态栏的外观和行为

### Status Bar:
### 状态栏：

# Read `man 5 sway-bar` for more information about this section.
# 阅读 `man 5 sway-bar` 获取此部分的更多信息。

bar {
    swaybar_command waybar
    # position top

    # # When the status_command prints a new line to stdout, swaybar updates.
    # # The default just shows the current date and time.
    # # 当 status_command 向 stdout 打印新行时，swaybar 会更新。
    # # 默认只显示当前日期和时间。
    # status_command while date +'%Y-%m-%d %X'; do sleep 1; done

    # colors {
    #     statusline #ffffff
    #     background #323232
    #     inactive_workspace #32323200 #32323200 #5c5c5c
    # }
}
