# Applications Configuration
# 应用程序配置
#
# Configure application startup, environment variables, and system services
# 配置应用程序启动、环境变量和系统服务

### Application startup
### 应用程序启动

# 启动壁纸
exec swww-daemon

# 设置语言环境
exec --no-startup-id export LANG=en_US.UTF-8

# Clipboard manager
# 剪贴板管理器2
#exec wl-paste -t text --watch clipman store --no-persist
# 让 cliphist 在后台存储文本历史
exec wl-paste --type text --watch cliphist store
# 让 cliphist 在后台存储图像历史
exec wl-paste --type image --watch cliphist store


# Bluetooth applet
# 蓝牙小程序
exec --no-startup-id blueman-applet

# Proxy application
# 代理应用程序
exec clash-verge

# Input method
# 输入法
exec_always fcitx5 -d
#exec_always pkill fcitx5
#exec fcitx5 -d
### Environment variables
### 环境变量

# Set input method environment variables
# 设置输入法环境变量
exec --no-startup-id export GTK_IM_MODULE=fcitx
exec --no-startup-id export QT_IM_MODULE=fcitx
exec --no-startup-id export XMODIFIERS=@im=fcitx

# 解决微信弹窗焦点问题
no_focus [class="^(wechat|termora|geogebra)$"]


# 配置 sway 自动启动通知守护进程
exec swaync
