# 三指向上滑动切换到上一个工作区
bindgesture swipe:3:up workspace prev

# 三指向下滑切换到下一个工作区
bindgesture swipe:3:down workspace next

# 三指向左滑动移动到左侧工作区
bindgesture swipe:3:left workspace left

# 三指向右滑动移动到右侧工作区
bindgesture swipe:3:right workspace right
#----------------------------------------

# 四指向上滑动最大化窗口
bindgesture swipe:4:up fullscreen toggle

# 四指向下滑动最小化窗口
bindgesture swipe:4:down move scratchpad

# 四指向左滑动将窗口移至左侧工作区
bindgesture swipe:4:left move container to workspace left

# 四指向右滑动将窗口移至右侧工作区
bindgesture swipe:4:right move container to workspace right

#----------------------------------------

# 两指捏合缩小窗口（水平方向）
#bindgesture pinch:2:inward resize shrink width 10 px or 10 ppt

# 两指张开放大窗口（水平方向）
#bindgesture pinch:2:outward resize grow width 10 px or 10 ppt

#----------------------------------------

# 两指长按触发rofi启动器
#bindgesture hold:2 exec rofi -show drun

#----------------------------------------
#----------------------------------------
#----------------------------------------
#----------------------------------------
#----------------------------------------
#----------------------------------------
#----------------------------------------
